# Generated by Django 3.0.2 on 2020-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200405_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Star Wars', 'Star Wars'), ('Ninjago', 'Ninjago'), ('City', 'City'), ('Minecraft', 'Minecraft'), ('Series', 'Series'), ('Classic', 'Classic'), ('MOC', 'MOC'), ('Khác', 'Khác')], max_length=50),
        ),
    ]
