# Generated by Django 3.0.2 on 2020-04-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200405_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('on', 'ongoing'), ('off', 'finished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_takes_place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
