# Generated by Django 3.0.2 on 2020-04-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
