# Generated by Django 3.0.2 on 2020-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20200419_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Ninjago', 'Ninjago'), ('City', 'City'), ('Động vật', 'Động vật'), ('Fantasy', 'Fantasy'), ('Star Wars', 'Star Wars'), ('Minecraft', 'Minecraft'), ('Overwatch', 'Overwatch'), ('Xe-Máy bay', 'Xe-Máy bay'), ('Custom', 'Custom'), ('Technic', 'Technic'), ('Rồng', 'Rồng'), ('Lâu Đài', 'Lâu Đài'), ('CyberPunk', 'CyberPunk'), ('DC', 'DC'), ('Marvel', 'Marvel'), ('Vòng tay', 'Vòng tay'), ('Tủ đựng', 'Tủ đựng'), ('Hộp kính', 'Hộp kính'), ('Móc chìa khóa', 'Móc chìa khóa'), ('Gạch', 'Gạch')], max_length=50),
        ),
    ]
