# Generated by Django 3.0.2 on 2020-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20200419_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Ninjago', 'Ninjago'), ('City', 'City'), ('Animal', 'Animal'), ('Fantasy', 'Fantasy'), ('Star_Wars', 'Star_Wars'), ('Minecraft', 'Minecraft'), ('Overwatch', 'Overwatch'), ('Vehicle', 'Vehicle'), ('Custom', 'Custom'), ('Technic', 'Technic'), ('Dragon', 'Dragon'), ('Castle', 'Castle'), ('CyberPunk', 'CyberPunk'), ('DC', 'DC'), ('Marvel', 'Marvel'), ('Bracelet', 'Bracelet'), ('Chest', 'Chest'), ('Glass_Box', 'Glass_Box'), ('Key_Chain', 'Key_Chain'), ('Brick', 'Brick')], max_length=50),
        ),
    ]
