# Generated by Django 3.0.2 on 2020-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20200419_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ninjago', 'ninjago'), ('city', 'city'), ('animal', 'animal'), ('fantasy', 'fantasy'), ('star_wars', 'star_wars'), ('minecraft', 'minecraft'), ('overwatch', 'overwatch'), ('vehicle', 'vehicle'), ('custom', 'custom'), ('technic', 'technic'), ('dragon', 'dragon'), ('castle', 'castle'), ('cyberpunk', 'cyberpunk'), ('dc', 'dc'), ('marvel', 'marvel'), ('bracelet', 'bracelet'), ('chest', 'chest'), ('glass_box', 'glass_box'), ('key_chain', 'key_chain'), ('brick', 'brick')], max_length=50),
        ),
    ]
