# Generated by Django 3.0.2 on 2020-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20200419_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Event', 'Event'), ('Notify', 'Notify')], default='Event', max_length=10),
        ),
    ]
