# Generated by Django 3.0.2 on 2020-04-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20200419_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='Info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Không có mô tả nào', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.CharField(default='Không có lưu ý nào', max_length=100, null=True),
        ),
    ]
