# Generated by Django 3.0.2 on 2020-04-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20200421_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Info',
        ),
        migrations.AddField(
            model_name='post',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ImagesOfPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.Post')),
            ],
        ),
    ]
