# Generated by Django 3.0.2 on 2020-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='buyer',
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
