# Generated by Django 3.0.2 on 2020-04-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_auto_20200423_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
