# Generated by Django 3.0.2 on 2020-04-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
