# Generated by Django 3.0.2 on 2020-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20200425_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='address',
            field=models.TextField(default='Chưa có'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='phonenumber',
            field=models.CharField(default='Chưa có', max_length=10),
        ),
    ]
