# Generated by Django 3.0.2 on 2020-04-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20200425_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='address',
            field=models.TextField(blank=True, default='Chưa có', null=True),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='phonenumber',
            field=models.CharField(blank=True, default='Chưa có', max_length=10, null=True),
        ),
    ]
