# Generated by Django 3.0.2 on 2020-04-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20200425_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoUser',
        ),
    ]
