# Generated by Django 3.0.2 on 2020-04-26 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0050_infouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
