# Generated by Django 3.0.2 on 2020-04-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_auto_20200426_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
