# Generated by Django 3.0.2 on 2020-04-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_infouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
