# Generated by Django 3.0.2 on 2020-04-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
