# Generated by Django 3.0.2 on 2020-04-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_auto_20200429_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
