# Generated by Django 3.0.2 on 2020-04-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartOrder',
        ),
    ]
