# Generated by Django 3.0.2 on 2020-05-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_auto_20200430_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_views',
            field=models.IntegerField(null=True),
        ),
    ]
