# Generated by Django 3.0.2 on 2020-05-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_post_count_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_views',
        ),
    ]
