# Generated by Django 3.0.2 on 2020-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_remove_post_count_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_views',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='step',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
