# Generated by Django 3.0.2 on 2020-05-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_auto_20200501_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_views',
        ),
        migrations.RemoveField(
            model_name='post',
            name='step',
        ),
    ]
