# Generated by Django 3.0.2 on 2020-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0071_auto_20200503_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('event', 'event'), ('notify', 'notify')], default='Event', max_length=10),
        ),
    ]
